INSERT INTO story (storyid, title, url) VALUES (1, 'Realtek RTL836x series of Ethernet switch ICs has a 8051 hidden inside', 'https://twitter.com/whitequark/status/1175701730819895296');
INSERT INTO story (storyid, title, url) VALUES (2, 'I made a neural net that analyzes privacy policies', 'https://useguard.com/');
INSERT INTO story (storyid, title, url) VALUES (3, 'Four common mistakes in audio development', 'http://atastypixel.com/blog/four-common-mistakes-in-audio-development/');
INSERT INTO story (storyid, title, url) VALUES (4, 'Hacking the Brain', 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6429408/');
INSERT INTO story (storyid, title, url) VALUES (5, '	ProtoThreads: Lightweight, Stackless Threads in C', 'http://dunkels.com/adam/pt/');
INSERT INTO story (storyid, title, url) VALUES (6, 'American Emergency Rooms Confront a Crisis of Violence', 'https://www.city-journal.org/violence-in-americas-emergency-rooms');
INSERT INTO story (storyid, title, url) VALUES (7, '	Some WeWork Board Members Seek to Remove Adam Neumann as CEO', 'https://www.wsj.com/articles/some-wework-board-members-seek-to-remove-adam-neumann-as-ceo-11569171188?mod=rsswn');
INSERT INTO story (storyid, title, url) VALUES (8, 'Reverse-engineering precision op amps from a 1969 analog computer', 'https://www.righto.com/2019/09/reverse-engineering-precision-op-amps.html');
INSERT INTO story (storyid, title, url) VALUES (9, 'Using Gooey as a Universal Front End for Any Language or CLI Application', 'https://chriskiehl.com/article/gooey-as-a-universal-frontend');
INSERT INTO story (storyid, title, url) VALUES (10, 'NUMA Optimisations in FreeBSD Helped Netflix Serve 200Gbps of Video / Server [pdf] ', 'https://people.freebsd.org/~gallatin/talks/euro2019.pdf');
INSERT INTO story (storyid, title, url) VALUES (11, 'A Burning B-52 Nearly Caused A Nuclear Catastrophe', 'https://www.thedrive.com/the-war-zone/29945/the-time-when-a-burning-b-52-nearly-caused-a-nuclear-catastrophe-worse-than-chernobyl');
INSERT INTO story (storyid, title, url) VALUES (12, '	A synthetic metabolic network for physicochemical homeostasis', 'https://www.nature.com/articles/s41467-019-12287-2');
INSERT INTO story (storyid, title, url) VALUES (13, 'A Blue Collar Slob’s Introduction to the Rare Oakland Manzanita', 'https://www.youtube.com/watch?v=-tpWrX-XlBQ');
INSERT INTO story (storyid, title, url) VALUES (14, 'Topological Weyl fermion lines and drumhead surface states in room temp magnet', 'https://science.sciencemag.org/content/365/6459/1278');
INSERT INTO story (storyid, title, url) VALUES (15, 'Understanding the working of X11 from the ground up (2017)', 'https://magcius.github.io/xplain/article/index.html');
INSERT INTO story (storyid, title, url) VALUES (16, 'Viable Quantum Supercomputer ', 'https://drive.google.com/file/d/19lv8p1fB47z1pEZVlfDXhop082Lc-kdD/view');
INSERT INTO story (storyid, title, url) VALUES (17, 'Free42: An HP-42S Calculator Simulator (2005)', 'https://github.com/thomasokken/free42');
INSERT INTO story (storyid, title, url) VALUES (18, 'Brains are the last frontier of privacy', 'https://www.axios.com/robotic-brains-data-technology-companies-6ba7269e-1553-4395-a6db-3560fead7e24.html');
INSERT INTO story (storyid, title, url) VALUES (19, 'A Son’s Race to Give His Dying Father Artificial Immortality (2017)', 'https://www.wired.com/story/a-sons-race-to-give-his-dying-father-artificial-immortality/');
INSERT INTO story (storyid, title, url) VALUES (20, 'The ReMarkable Tablet: A Review', 'https://blog.liw.fi/posts/2019/09/22/the_remarkable_tablet_a_review/');
INSERT INTO story (storyid, title, url) VALUES (21, 'Facebook to acquire CTRL-Labs, a startup for controlling computers with the mind', 'https://www.bloomberg.com/news/articles/2019-09-23/facebook-to-buy-startup-for-controlling-computers-with-your-mind');
INSERT INTO story (storyid, title, url) VALUES (22, 'Brain research on boys’ preference for video games and girls’ for social media', 'https://www.wsj.com/articles/girls-vs-boys-brain-differences-might-explain-tech-behaviors-11569317402');
INSERT INTO story (storyid, title, url) VALUES (23, 'The London Review of Books at 40', 'https://www.theguardian.com/books/2019/sep/21/london-review-of-books-at-40-susannah-clapp');
INSERT INTO story (storyid, title, url) VALUES (24, 'MegaBots calls it a day, puts fighting robot up for sale on eBay', 'https://techcrunch.com/2019/09/24/megabots-calls-it-a-day-puts-fighting-robot-up-for-sale-on-ebay/');
INSERT INTO story (storyid, title, url) VALUES (25, 'A Eulogy for Objective-C (2015)', 'https://academy.realm.io/posts/altconf-aaron-hillegass-eulogy-for-objective-c/');
INSERT INTO story (storyid, title, url) VALUES (26, 'iPadOS', 'https://www.apple.com/ipados/');
INSERT INTO story (storyid, title, url) VALUES (27, 'CentOS Stream', 'https://www.redhat.com/en/blog/transforming-development-experience-within-centos');
INSERT INTO story (storyid, title, url) VALUES (28, 'Thomas Cook Shuts Down', 'https://www.wsj.com/articles/thomas-cook-enters-compulsory-liquidation-11569206090?mod=rsswn');
INSERT INTO story (storyid, title, url) VALUES (29, 'Rent control will make housing shortages worse', 'https://www.economist.com/leaders/2019/09/19/rent-control-will-make-housing-shortages-worse');
INSERT INTO story (storyid, title, url) VALUES (30, 'Coder deletes open source add-on for Chef in protest over ICE contract', 'https://arstechnica.com/information-technology/2019/09/coder-deletes-open-source-add-on-for-chef-in-protest-over-ice-contract/');
INSERT INTO story (storyid, title, url) VALUES (31, 'Competitors are throwing everything at the wall to slow the Amazon juggernaut', 'https://arstechnica.com/tech-policy/2019/09/walmart-oracle-and-mall-owner-simon-behind-grassoots-anti-amazon-org/');
INSERT INTO story (storyid, title, url) VALUES (32, '“Information gerrymandering” influences voters', 'http://news.mit.edu/2019/information-gerrymandering-influences-voters-0904');
INSERT INTO story (storyid, title, url) VALUES (33, 'Gene name errors are widespread in the scientific literature (2016)', 'https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-1044-7');
INSERT INTO story (storyid, title, url) VALUES (34, 'Supreme Court: Suspending Parliament was unlawful, judges rule', 'https://www.bbc.co.uk/news/uk-politics-49810261');
INSERT INTO story (storyid, title, url) VALUES (35, 'Macron Secures €5B Investment to Boost French Tech Startups', 'https://www.wsj.com/articles/macron-secures-5-billion-investment-to-boost-french-tech-startups-11568749343?mod=rsswn');
INSERT INTO story (storyid, title, url) VALUES (36, 'For Airbnb employees, dream turns into disillusionment', 'https://www.sfgate.com/business/article/For-Airbnb-Employees-Dream-Turns-Into-14457034.php');
INSERT INTO story (storyid, title, url) VALUES (37, 'Six Ex–Government Scientists Explain What It Was Like to Work for Trump', 'https://slate.com/technology/2019/09/climate-change-trump-epa-interior-whistleblowers-science.html');
INSERT INTO story (storyid, title, url) VALUES (38, 'Hold That Recession: U.S. Indicators Are Trouncing Forecasts', 'https://www.bloomberg.com/news/articles/2019-09-20/hold-that-recession-u-s-indicators-are-trouncing-forecasts');
INSERT INTO story (storyid, title, url) VALUES (39, 'The Showdown at the Window Seat', 'https://www.wsj.com/articles/the-showdown-at-the-window-seat-11568799003');
INSERT INTO story (storyid, title, url) VALUES (40, 'Former developer at software company deletes his code to protest its ties to ICE', 'https://www.dailydot.com/irl/former-chef-developer-deletes-code-ice/');
INSERT INTO story (storyid, title, url) VALUES (41, 'NY Fed to pump $75 bn into money markets daily through Oct 10', 'https://news.yahoo.com/ny-fed-pump-75-bn-money-markets-daily-154943871.html');
INSERT INTO story (storyid, title, url) VALUES (42, 'CentOS Stream and CentOS Linux 8 Released', 'https://centos.org/');
INSERT INTO story (storyid, title, url) VALUES (43, 'Want to Reduce Suicides? Follow the Data to Medical Offices, Motels, etc.', 'https://khn.org/news/want-to-reduce-suicides-follow-the-data-to-medical-offices-motels-and-even-animal-shelters/');
INSERT INTO story (storyid, title, url) VALUES (44, 'Google Claims "Quantum Supremacy"', 'https://fortune.com/2019/09/20/google-claims-quantum-supremacy/');
INSERT INTO story (storyid, title, url) VALUES (45, '250k kilometers of Saturn''s rings animated as a perspective fly-over [video]', 'https://www.youtube.com/watch?v=ac1i4iOg5rs');
INSERT INTO story (storyid, title, url) VALUES (46, 'I’m Dealing with Imposter Syndrome and Stress', 'http://www.helenanderson.co.nz/imposter-syndrome-stress/');
INSERT INTO story (storyid, title, url) VALUES (47, 'Cities Across the World Flash the Bat Signal on Batman Day', 'https://edition.cnn.com/2019/09/21/world/batman-day-signal-trnd/index.html');
INSERT INTO story (storyid, title, url) VALUES (48, 'Googles API examples still with Python2', 'https://imgur.com/a/7lckYog');
INSERT INTO story (storyid, title, url) VALUES (49, 'Neil Young’s failed anti-streaming business helped the music industry', 'https://qz.com/1711629/how-neil-youngs-business-failure-helped-the-the-music-industry/');
INSERT INTO story (storyid, title, url) VALUES (50, 'Build an NB-IoT GPS Tracker on STM32 L476 with Apache Mynewt and Embedded Rust', 'https://medium.com/@ly.lee/build-an-nb-iot-gps-tracker-on-stm32-l476-with-apache-mynewt-and-embedded-rust-8c095a925546');
INSERT INTO story (storyid, title, url) VALUES (51, 'Hong Kong police "pushed to the limit"', 'https://www.bbc.com/news/world-asia-49774809');
INSERT INTO story (storyid, title, url) VALUES (52, 'Chelsea M. imprisoned for 6 months for refusing to testify against Julian A', 'https://www.wsws.org/en/articles/2019/09/21/pers-s21.html');
INSERT INTO story (storyid, title, url) VALUES (53, 'Greta Thunberg speech: How dare you? [video]', 'https://m.youtube.com/watch?v=TMrtLsQbaok');
INSERT INTO story (storyid, title, url) VALUES (54, 'Two Israeli Brothers Arrested for Phishing Fraud, Bitfinex Hack', 'https://www.coindesk.com/two-israeli-brothers-arrested-for-phishing-fraud-bitfinex-hack');
INSERT INTO story (storyid, title, url) VALUES (55, 'Google Claims "Quantum Supremacy," Marking a Major Milestone in Computing', 'https://fortune.com/2019/09/20/google-claims-quantum-supremacy/');
INSERT INTO story (storyid, title, url) VALUES (56, 'CGPGrey"s YouTube account has been suspended', 'https://twitter.com/cgpgrey/status/1175681091165966336');
INSERT INTO story (storyid, title, url) VALUES (57, 'The U.S. China Trade War May Cause Multipolarity Instead of Deglobalisation', 'https://medium.com/discourse/the-u-s-china-trade-war-may-cause-multipolarity-instead-of-deglobalisation-b8e108a47965');
INSERT INTO story (storyid, title, url) VALUES (58, 'Dragon Con co-founder indicted in computer hacking case', 'https://www.11alive.com/article/news/crime/ed-kramer-judge-schrader-gwinnett-indictment/85-e0031b88-ef90-4674-922e-b225ff366598');
INSERT INTO story (storyid, title, url) VALUES (59, 'I Invented a Better Windshield Wiper and a $2M/Year Business', 'https://www.starterstory.com/scrubblade');
INSERT INTO story (storyid, title, url) VALUES (60, 'Facebook Employee Suicide Cover-Up', 'https://www.youtube.com/watch?v=VbEQriZEfoI');
INSERT INTO story (storyid, title, url) VALUES (61, 'Protein tangles linked with dementia seen in patients after single head injury', 'https://www.sciencedaily.com/releases/2019/09/190905103013.htm');
INSERT INTO story (storyid, title, url) VALUES (62, 'WeWork, Bankers Have Discussed Laying Off One-Third of Workforce', 'https://www.theinformation.com/articles/wework-bankers-have-discussed-laying-off-one-third-of-workforce');
INSERT INTO story (storyid, title, url) VALUES (63, 'In How To: Xkcd author offers absurd advice for ordinary tasks', 'https://arstechnica.com/science/2019/09/how-to-a-funny-instruction-manual-for-the-terminally-curious-or-super-villains/');
INSERT INTO story (storyid, title, url) VALUES (64, 'Medicine show: Crown Sterling demos 256-bit RSA key-cracking at private event', 'https://arstechnica.com/information-technology/2019/09/medicine-show-crown-sterling-demos-256-bit-rsa-key-cracking-at-private-event/');
INSERT INTO story (storyid, title, url) VALUES (65, 'Bill Gates: The Scam Behind Her Foundation', 'https://www.youtube.com/watch?v=Dqzt6yAmdDE');
INSERT INTO story (storyid, title, url) VALUES (66, 'The American working man still isn’t working', 'https://www.foreignaffairs.com/articles/united-states/2019-09-19/american-working-man-still-isnt-working');
INSERT INTO story (storyid, title, url) VALUES (67, 'Russia adopts Paris climate agreement: decree', 'https://www.france24.com/en/20190923-russia-adopts-paris-climate-agreement-decree');
INSERT INTO story (storyid, title, url) VALUES (68, 'Vikings Went into a Trancelike Rage Before Battle', 'https://www.wired.com/story/how-vikings-went-into-trancelike-rage-before-battle/');
INSERT INTO story (storyid, title, url) VALUES (69, 'Stern warning from Microsoft against using Chrome 78 Beta', 'https://www.reddit.com/r/sysadmin/comments/d6q76g/stern_warning_from_microsoft_against_using_chrome/');
INSERT INTO story (storyid, title, url) VALUES (70, 'Boeing"s Managerial Revolution Created the 737 Max Disaster', 'https://newrepublic.com/article/154944/boeing-737-max-investigation-indonesia-lion-air-ethiopian-airlines-managerial-revolution?src=longreads');
INSERT INTO story (storyid, title, url) VALUES (71, 'Rumors hint that Google has accomplished quantum supremacy', 'https://www.sciencenews.org/article/rumors-hint-that-google-has-accomplished-quantum-supremacy');
INSERT INTO story (storyid, title, url) VALUES (72, 'PyTorch – Tensor computation with strong GPU acceleration', 'https://pytorch.org/');
INSERT INTO story (storyid, title, url) VALUES (73, 'Small Trial Reverses a Year of Alzheimer"s Cognitive Decline in Just Two Months', 'https://www.sciencealert.com/small-trial-reverses-a-year-of-alzheimer-s-in-just-two-months-in-seven-patients');
INSERT INTO story (storyid, title, url) VALUES (74, 'Fungi Basidiomycetes can be used as computing devices', 'https://royalsocietypublishing.org/doi/full/10.1098/rsfs.2018.0029');
INSERT INTO story (storyid, title, url) VALUES (75, 'Jonathan Ledgard Believes Imagination Could Save the World', 'https://www.newyorker.com/magazine/2019/09/23/jonathan-ledgard-believes-imagination-could-save-the-world');
INSERT INTO story (storyid, title, url) VALUES (76, 'What can a software developer do about climate change?', 'https://codewithoutrules.com/2019/09/10/software-developers-climage-change/');
INSERT INTO story (storyid, title, url) VALUES (77, 'UVB-76 the Buzzer according to Russian ex servicemen', 'https://www.numbers-stations.com/articles/uvb-76-the-buzzer-according-to-russian-ex-servicemen/');
INSERT INTO story (storyid, title, url) VALUES (78, 'Facebook Restricts Free Speech by Popular Demand', 'https://www.theatlantic.com/ideas/archive/2019/09/facebook-restricts-free-speech-popular-demand/598462/');
INSERT INTO story (storyid, title, url) VALUES (79, 'Few things are as dangerous as economists with physics envy (2018)', 'https://aeon.co/ideas/few-things-are-as-dangerous-as-economists-with-physics-envy');
INSERT INTO story (storyid, title, url) VALUES (80, 'Saudi Aramco hires UBS, Deutsche as bookrunners for its IPO', 'https://www.reuters.com/article/us-saudi-aramco-banks/saudi-aramco-hires-ubs-deutsche-as-bookrunners-for-its-ipo-sources-idUSKBN1W608C');
INSERT INTO story (storyid, title, url) VALUES (81, 'Emissions Impact of Having 1 Less Child', 'https://iopscience.iop.org/article/10.1088/1748-9326/aa7541');
INSERT INTO story (storyid, title, url) VALUES (82, 'Google creates world’s most powerful computer, NASA ‘accidentally reveals’', 'https://www.rt.com/usa/469325-google-quantum-computer-reports/');
INSERT INTO story (storyid, title, url) VALUES (83, 'Systemd-Homed: Systemd Now Working to Improve Home Directory Handling', 'https://www.phoronix.com/scan.php?page=news_item&px=systemd-homed');
INSERT INTO story (storyid, title, url) VALUES (84, 'Mental Models to Make You a Worldly Wise Person', 'https://medium.com/swlh/100-mental-models-to-make-you-a-worldly-wise-person-19b9ca9d034c');
INSERT INTO story (storyid, title, url) VALUES (85, 'The YouTube Revolution in Knowledge Transfer', 'https://www.lesswrong.com/posts/RXLbe6oZGxNWvQawn/the-youtube-revolution-in-knowledge-transfer');
INSERT INTO story (storyid, title, url) VALUES (86, 'GitLens: Where have you been all my life', 'https://dev.to/glsolaria/gitlens-where-have-you-been-all-my-life-1c2d');
INSERT INTO story (storyid, title, url) VALUES (87, 'What’s Faster? Count(*) Or COUNT(1)?', 'https://blog.jooq.org/2019/09/19/whats-faster-count-or-count1/');
INSERT INTO story (storyid, title, url) VALUES (88, 'iFixit’s iPhone 11 Pro Max teardown finds higher-capacity battery, 4GB of RAM', 'https://arstechnica.com/gadgets/2019/09/ifixits-iphone-11-pro-max-teardown-finds-larger-battery-4gb-of-ram/');
INSERT INTO story (storyid, title, url) VALUES (89, 'Footage of hundreds of blindfolded, shackled Uighur prisoners in Xinjiang, China', 'https://www.theguardian.com/world/2019/sep/23/china-footage-reveals-hundreds-of-blindfolded-and-shackled-prisoners-uighur');
INSERT INTO story (storyid, title, url) VALUES (90, 'The Exponent IPO [audio]', 'https://exponent.fm/episode-173-the-exponent-ipo/');
INSERT INTO story (storyid, title, url) VALUES (91, 'An AI learned to play hide-and-seek. Strategies it came up with were astounding', 'https://www.vox.com/future-perfect/2019/9/20/20872672/ai-learn-play-hide-and-seek');
INSERT INTO story (storyid, title, url) VALUES (92, 'An Edit-Centric Approach for Wikipedia Article Quality Assessment', 'https://arxiv.org/abs/1909.08880');
INSERT INTO story (storyid, title, url) VALUES (93, 'Went to update payment info, showed me some random person’s credit card info', 'https://reddit.com/r/ios/comments/d7u91h/went_to_update_payment_info_showed_me_some_random/');
INSERT INTO story (storyid, title, url) VALUES (94, 'Protein tangles linked with dementia seen in patients after single head injury', 'https://www.sciencedaily.com/releases/2019/09/190905103013.htm');
INSERT INTO story (storyid, title, url) VALUES (95, 'Sanders wants to replace credit reporting companies with public credit registry', 'https://www.vox.com/2019/9/21/20877050/bernie-sanders-credit-score-equifax-transunion-experian');
INSERT INTO story (storyid, title, url) VALUES (96, 'HCL anti-union tech works', 'https://www.theguardian.com/technology/2019/sep/23/google-pittsburgh-union-roots-transform-tech-industry');
INSERT INTO story (storyid, title, url) VALUES (97, 'Why is pipenv the recommended packaging tool by the community and PyPA?: Python', 'https://www.reddit.com/r/Python/comments/8jd6aq/why_is_pipenv_the_recommended_packaging_tool_by/');
INSERT INTO story (storyid, title, url) VALUES (98, 'The Internet of Things Is Still a Privacy Dumpster Fire, Study Finds', 'https://www.vice.com/en_us/article/gyzjym/the-internet-of-things-is-still-a-privacy-dumpster-fire-study-finds');
INSERT INTO story (storyid, title, url) VALUES (99, 'Quake speedrun record broken after 17 years', 'https://www.youtube.com/watch?v=43d8fICz6gM');
INSERT INTO story (storyid, title, url) VALUES (100, 'Reinventing Home Directories', 'https://media.ccc.de/v/ASG2019-164-reinventing-home-directories');
INSERT INTO story (storyid, title, url) VALUES (101, 'Untitled Goose Game adapted Debussy for its dynamic soundtrack', 'https://www.theverge.com/2019/9/23/20879792/untitled-goose-game-nintendo-switch-debussy');
INSERT INTO story (storyid, title, url) VALUES (102, 'It"s time programmers talked about ethics', 'https://tiny-giant-books.com/Entry3.html?EntryId=recJgpI5Fi77utG7Z');
INSERT INTO story (storyid, title, url) VALUES (103, 'Lightweight (~17KB) React/TypeScript Charting Lib with Storybook Playground', 'https://github.com/sheshbabu/react-frappe-charts#readme');
INSERT INTO story (storyid, title, url) VALUES (104, 'First They Took Our Headphone Jack, Now They’re Taking Our Volume Buttons', 'https://www.tomsguide.com/news/first-they-took-our-headphone-jack-now-theyre-taking-our-volume-buttons');
INSERT INTO story (storyid, title, url) VALUES (105, 'WeWork CEO, Adam Neumann, Stepping Down Under Pressure', 'https://www.nytimes.com/2019/09/24/business/dealbook/wework-ceo-adam-neumann.html');
INSERT INTO story (storyid, title, url) VALUES (106, 'Netflix – Evolving Regional Evacuation', 'https://medium.com/@NetflixTechBlog/evolving-regional-evacuation-69e6cc1d24c6');
INSERT INTO story (storyid, title, url) VALUES (107, 'Show HN: CC Time is a simple and unobtrusive time tracking utility', 'https://github.com/rlv-dan/CCTime');
INSERT INTO story (storyid, title, url) VALUES (108, 'Poverty changes your brain to make you less intelligent, study suggests (2016)', 'https://www.independent.co.uk/news/science/poverty-intelligence-aging-brain-low-income-inequality-a7333506.html');
INSERT INTO story (storyid, title, url) VALUES (109, 'IKEA will produce more energy than it consumes by 2020', 'https://www.engadget.com/2019/09/22/ikea-energy-positive-by-2020/');
INSERT INTO story (storyid, title, url) VALUES (110, 'Show HN: TimeQ, time tracking and invoicing software for freelancers', 'https://timeq.co');
INSERT INTO story (storyid, title, url) VALUES (111, 'A Lot of Rules', 'https://blog.jessitron.com/2019/09/23/a-lot-of-rules/');
INSERT INTO story (storyid, title, url) VALUES (112, 'Show HN: Komplish – Turn your todo list into your Résumé', 'https://www.komplish.com');

alter sequence hibernate_sequence restart with 25;
